input:
  images:
    - /raw/images/USA_99.jpg
    - /raw/images/BLR_99.jpg
    - /raw/images/MEX_99.jpg
    - /raw/images/BGR_99.jpg
    - /raw/images/ITA_99.jpg

model:
  detector: /src/models/prod_models/yolo/mrz_detector_v2_int8_openvino_model
  classifier: /src/models/prod_models/yolo/best_classify.pt

pipeline:
  ocr: tesseract
  checker: true

run:
  device: cpu
  verbose: false
  imgsz: 320