input:
  images:
    - input/BEL_11.jpg
    - input/BLR_29.jpg
    - input/UZB_83.jpg
    - input/UZB_94.jpg
    - input/BLR_6.jpg

model:
  detector: /src/models/prod_models/yolo/mrz_detector_v2_int8_openvino_model
  classifier: /src/models/prod_models/yolo/best_classify.pt

pipeline:
  ocr: tesseract
  checker: true

run:
  device: cpu
  verbose: false
  imgsz: 320